version: "3.7"
services:
  frontend:
    image: node-reaper-frontend
    volumes:
      - ./frontend:/working
    working_dir: /working

  backend:
    image: node-reaper-backend
    volumes:
      - .:/working
      - ~/.aws:/root/.aws
      - gradle_cache:/home/gradle/.gradle/caches
    working_dir: /working

volumes:
  gradle_cache:
