version: "3.7"
services:
  gradle:
    image: gradle:6.0.1
    volumes:
      - .:/working
      - ~/.aws:/root/.aws
      - gradle_cache:/home/gradle/.gradle/caches
    working_dir: /working

volumes:
  gradle_cache:
